name: Format

on: [push, pull_request]

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Format
        run: yarn format
